image: peterzuger/arch-dev

build:
  script:
    - make clean && make TARGET_NAME=libcm0  ARCH=thumb  SYS=none  CPU=cortex-m0
    - make clean && make TARGET_NAME=libcm0p ARCH=thumb  SYS=none  CPU=cortex-m0plus
    - make clean && make TARGET_NAME=libcm3  ARCH=thumb  SYS=none  CPU=cortex-m3
    - make clean && make TARGET_NAME=libcm4  ARCH=thumb  SYS=none  CPU=cortex-m4
    - make clean && make TARGET_NAME=libcm7  ARCH=thumb  SYS=none  CPU=cortex-m7
    - make clean && make TARGET_NAME=libc    ARCH=x86_64 SYS=linux CPU=native
  artifacts:
    paths:
      - libcm0.a
      - libcm0p.a
      - libcm3.a
      - libcm4.a
      - libcm7.a
      - libc.a
